CREATE TABLE "SightingPreviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Species" text,
    "Breed" text,
    "ImageUrl" text,
    "LastSpotted" timestamp with time zone NOT NULL,
    "Coordinates_Latitude" double precision,
    "Coordinates_Longitude" double precision,
    "SubmittedById" text NOT NULL,
    CONSTRAINT "PK_SightingPreviews" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250508193044_AddedSightingPreview', '9.0.3');

COMMIT;

